name: Deploy MultiDocker
on:
  push:
    branches:
      - master # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sahayavijay/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sahayavijay/react-test npm test

      - run: docker build -t sahayavijay/fib-client ./client
      - run: docker build -t sahayavijay/fib-nginx ./nginx
      - run: docker build -t sahayavijay/fib-server ./server
      - run: docker build -t sahayavijay/fib-worker ./worker

      - run: docker push sahayavijay/fib-client
      - run: docker push sahayavijay/fib-nginx
      - run: docker push sahayavijay/fib-server
      - run: docker push sahayavijay/fib-worker

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
