name: CI Pipeline

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build test image
        run: docker build -f client/Dockerfile.dev -t test-image ./client

      - name: Run tests ( Only in Client, we can setup for all services too )
        run: docker run -e CI=true test-image npm test
  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [client, nginx, server, worker]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login into Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Production Image
        run: |
          docker build \
            -f ./${{ matrix.service }}/Dockerfile \
            -t sahayavijay/fib-${{ matrix.service }}:latest \
            ./${{ matrix.service }}

      - name: Push the Image
        run: Docker push sahayavijay/fib-${{ matrix.service }}:latest
